version: '3.0'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.1
    environment:
      - monitoring.elasticsearch.hosts=http://es:9200
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elastic
  kinana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge
